# Generated by Django 2.0.4 on 2018-06-11 10:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=5)),
                ('additional_info', models.CharField(blank=True, default='', help_text='Hinterhaus, c/o etc.', max_length=50, null=True)),
                ('city', models.CharField(help_text='Ortschaft', max_length=100)),
                ('postcode', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Bitte geben sie eine fünfstellige PLZ ein', regex='^.{5}$')])),
                ('latitude', models.FloatField(default=49.89873)),
                ('longitude', models.FloatField(default=10.90067)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titel des Angebots', max_length=100)),
                ('description', models.TextField(help_text='Beschreibung', max_length=300)),
                ('deposit', models.IntegerField(default=0, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('category', models.CharField(blank=True, choices=[('RO', 'Räume'), ('TO', 'Werkzeug'), ('EV', 'Eventequipment'), ('EL', 'Elektronik'), ('OF', 'Büroausstattung'), ('TR', 'Transportmittel'), ('HO', 'Küchengeräte'), ('SP', 'Sport & Spiel'), ('ME', 'Medien'), ('SE', 'Dienstleistungen und Wissen'), ('OT', 'Sonstiges')], default='OT', max_length=2, null=True)),
                ('lend_or_gift', models.CharField(choices=[('VL', 'Verleihen'), ('VS', 'Verschenken')], default='VL', max_length=2)),
                ('offerAdress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressApp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('einrichtungsname', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{8,15}')])),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ressApp.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(help_text='test', max_length=100)),
            ],
        ),
    ]
