# Generated by Django 2.0.4 on 2018-06-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offerImage',
            field=models.ImageField(default='static/ressApp/images/beamer.jpg', upload_to='static/ressApp/images'),
        ),
    ]
