# Generated by Django 2.0.4 on 2018-06-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressApp', '0002_offer_offerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerImage',
            field=models.ImageField(default='ressApp/static/ressApp/images/beamer.jpg', upload_to='ressApp/static/ressApp/images/offerImages'),
        ),
    ]
