# Generated by Django 2.0.2 on 2018-06-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressApp', '0005_auto_20180626_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerImage',
            field=models.ImageField(default='offer_image/beamer.jpg', upload_to='offer_image'),
        ),
    ]
