# Generated by Django 2.0.2 on 2018-06-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressApp', '0006_auto_20180626_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offerImage',
            field=models.ImageField(upload_to='offer_image'),
        ),
    ]
