# Generated by Django 2.0.2 on 2018-06-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressApp', '0007_auto_20180626_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offerImage',
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='offer_image/no_offer_image.jpg', upload_to='offer_image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_image/no_profile_image.jpg', upload_to='profile_image'),
        ),
    ]
